apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=crd
        - --domain-filter=gcp0.dev-ne.co
        - --provider=google
        - --google-project=neco-test
        - --registry=txt
        - --txt-owner-id=$(POD_NAME)
        - --log-format=json
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
