apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: argocd-server-selfsign
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: argocd-server-ca
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  secretName: argocd-server-ca
  duration: 87600h0m0s # 10y
  issuerRef:
    name: argocd-server-selfsign
  commonName: "ca.server.argocd"
  isCA: true
---
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: argocd-server-ca
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  ca:
    secretName: argocd-server-ca
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
spec:
  secretName: argocd-server-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: argocd-server-ca
  commonName: argocd.gcp0.dev-ne.co
  dnsNames:
    - argocd.gcp0.dev-ne.co
