apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-ingress.yaml
- argocd.yaml
- bmc-reverse-proxy.yaml
- cert-manager.yaml
- elastic.yaml
- external-dns.yaml
- ingress.yaml
- local-pv-provisioner.yaml
- maneki-apps.yaml
- metallb.yaml
- metrics-server.yaml
- monitoring.yaml
- namespaces.yaml
- neco-admission.yaml
- network-policy.yaml
- secrets.yaml
- team-management.yaml
- teleport.yaml
- topolvm.yaml
- rook.yaml
