apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: clouddns
spec:
  acme:
    email: neco@cybozu.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          clouddns:
            project: cybozu-neco
            serviceAccountSecretRef:
              key: account.json
              name: clouddns
        selector:
          dnsZones:
            - osaka0.cybozu-ne.co
