apiVersion: apps/v1
kind: Deployment
metadata:
  name: neco-admission
  namespace: kube-system
  labels:
    app.kubernetes.io/name: neco-admission
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neco-admission
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neco-admission
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - neco-admission
            topologyKey: cke.cybozu.com/rack
      containers:
      - name: neco-admission
        args:
        - --cert-dir=/certs
        - --httpproxy-default-class=forest
        image: quay.io/cybozu/neco-admission:0.4.3
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: config
            mountPath: /etc/neco-admission
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
            scheme: HTTP
      terminationGracePeriodSeconds: 10
      volumes:
        - name: certs
          secret:
            secretName: neco-admission-webhook
        - name: config
          configMap:
            name: neco-admission-config
---
apiVersion: v1
kind: Service
metadata:
  name: neco-admission
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: neco-admission
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
