apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: neco-admission
  annotations:
    cert-manager.io/inject-ca-from: kube-system/neco-admission
webhooks:
- name: mpod.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
      path: /mutate-pod
  failurePolicy: Fail
  objectSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values:
          - neco-admission
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
- name: mhttpproxy.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values: ["true"]
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
      path: /mutate-projectcontour-io-httpproxy
  failurePolicy: Fail
  rules:
  - apiGroups:
    - projectcontour.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - httpproxies
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: neco-admission
  annotations:
    cert-manager.io/inject-ca-from: kube-system/neco-admission
webhooks:
- name: vhttpproxy.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values: ["true"]
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
      path: /validate-projectcontour-io-httpproxy
  failurePolicy: Fail
  rules:
  - apiGroups:
    - projectcontour.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpproxies
- name: vnetworkpolicy.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values: ["true"]
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
      path: /validate-projectcalico-org-networkpolicy
  failurePolicy: Fail
  rules:
  - apiGroups:
    - crd.projectcalico.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkpolicies
- name: vapplication.kb.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values: ["true"]
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
      path: /validate-argoproj-io-application
  failurePolicy: Fail
  rules:
  - apiGroups:
    - argoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
