apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    openpolicyagent.org/webhook: ignore
    control-plane: "true"
    topolvm.cybozu.com/webhook: ignore
spec:
  finalizers:
    - kubernetes
