apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    control-plane: "true"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-for-ss
  labels:
    control-plane: "true"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-for-cs
  labels:
    control-plane: "true"
spec:
  finalizers:
    - kubernetes
