apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          image: quay.io/cybozu/cert-manager:0.14.2.1
          command:
          - cainjector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9402"
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          image: quay.io/cybozu/cert-manager:0.14.2.1
          command:
          - controller
          args:
          - --v=2
          - --cluster-resource-namespace=$(POD_NAMESPACE)
          - --leader-election-namespace=kube-system
          - --dns01-recursive-nameservers-only
          - --enable-certificate-owner-ref
          - --webhook-namespace=$(POD_NAMESPACE)
          - --webhook-ca-secret=cert-manager-webhook-ca
          - --webhook-serving-secret=cert-manager-webhook-tls
          - --webhook-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
          env:
          - name: NO_PROXY
            value: 10.0.0.0/8
          - name: HTTP_PROXY
            value: http://squid.internet-egress.svc.cluster.local:3128
          - name: HTTPS_PROXY
            value: http://squid.internet-egress.svc.cluster.local:3128
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          image: quay.io/cybozu/cert-manager:0.14.2.1
          command:
          - webhook
          volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
          - name: tmp
            mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
