{
 "title": "Sabakan",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Total Bytes of Images",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(images_bytes_total)" }
   ]
  },
  {
   "title": "Total Bytes of Assets",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(assets_bytes_total)" }
   ]
  },
  {
   "title": "Count of not healthy machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sabakan_machine_status{status!=\"healthy\"}) by (status)"
    }
   ]
  },
  {
   "title": "Count of healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sabakan_machine_status{status=\"healthy\"})"
    }
   ]
  }
 ]
}