{
 "title": "TopoLVM Volume Group",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total VG Free Capacity ",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "gbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(topolvm_volumegroup_available_bytes) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "VG Free Capacity",
   "type": "graph",
   "gridPos": { "h": 22, "w": 11, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "topolvm_volumegroup_available_bytes{node=~\"$node\"} / (1024 * 1024 * 1024)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Bottom 10 Nodes: VG Free Capacity",
   "type": "graph",
   "gridPos": { "h": 22, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, topolvm_volumegroup_available_bytes / (1024 * 1024 * 1024))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}