apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: folding-at-home
value: -10000
globalDefault: false
description: "This priority class should be used for low priority fah pods only."
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-1
  labels:
    app.kubernetes.io/name: folding-at-home-1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-1
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-2
  labels:
    app.kubernetes.io/name: folding-at-home-2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-2
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-3
  labels:
    app.kubernetes.io/name: folding-at-home-3
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-3
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-4
  labels:
    app.kubernetes.io/name: folding-at-home-4
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-4
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-5
  labels:
    app.kubernetes.io/name: folding-at-home-5
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-5
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: folding-at-home
  name: folding-at-home-6
  labels:
    app.kubernetes.io/name: folding-at-home-6
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: folding-at-home-6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: folding-at-home-6
    spec:
      securityContext:
        runAsUser: 101 # fahclient(=101)
      initContainers:
        - name: copy-config
          image: richstokes20/fah-covid:latest
          command: [cp, /etc/fahclient/config.xml, /config-volume/config.xml]
          volumeMounts:
          - mountPath: /config-volume
            name: config-volume
      containers:
        - name: fah
          image: richstokes20/fah-covid:latest
          imagePullPolicy: Always
          command:
            - /usr/bin/FAHClient
            - --config=/config-volume/config.xml
            - --run-as=fahclient
            - --pid-file=/var/run/fahclient.pid
            - --user=Cybozu
            - --proxy=squid.internet-egress.svc:3128
            - --proxy-enable
            - --power=full
            - --cpus=4
          env:
            - name: http_proxy
              value: http://squid.internet-egress.svc:3128
            - name: https_proxy
              value: http://squid.internet-egress.svc:3128
            - name: HTTP_PROXY
              value: http://squid.internet-egress.svc:3128
            - name: HTTPS_PROXY
              value: http://squid.internet-egress.svc:3128
          resources:
            limits:
              cpu: 4 # How much CPU you wish to donate per node
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - mountPath: /config-volume
              name: config-volume
              readOnly: false
            - mountPath: /opt/fah
              name: opt
              readOnly: false
            - mountPath: /var/lib/fahclient
              name: var-lib
              readOnly: false
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
        - name: var-lib
          emptyDir: {}
      priorityClassName: folding-at-home
