apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-issuer
  commonName: argocd.kind.cybozu-ne.co
  dnsNames:
    - argocd.kind.cybozu-ne.co
