# In Neco, metallb is run in L3 mode so we drop privileges required for L2 mode.

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: speaker
spec:
  privileged: false
  allowedCapabilities: []
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
