kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
        - $patch: delete
          name: install-cni
        - $patch: delete
          name: flexvol-driver
      containers:
        - name: calico-node
          image: quay.io/cybozu/calico:3.13.2.1
          command:
            - start_runit
          env:
            # Use "veth" instead of the default "cali" for Coil
            - name: FELIX_INTERFACEPREFIX
              value: "veth"
            - name: FELIX_PROMETHEUSMETRICSENABLED
              value: "true"
            - name: NO_PROXY
              value: localhost
          livenessProbe:
            exec:
              command:
              - calico-node
              - -felix-live
          readinessProbe:
            exec:
              command:
                - calico-node
                - -felix-ready
          volumeMounts:
            # workaround for writes to root filesystem
            - mountPath: /etc/service/enabled
              name: etc-service-enabled
              readOnly: false
            - $patch: delete
              mountPath: /var/run/nodeagent
      volumes:
        - name: etc-service-enabled
          emptyDir: {}
        - $patch: delete
          name: policysync
        - $patch: delete
          name: cni-bin-dir
        - $patch: delete
          name: cni-net-dir
        - $patch: delete
          name: flexvol-driver-host
