apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    kind: ClusterIssuer
    name: clouddns
  commonName: argocd.tokyo0.cybozu-ne.co
  dnsNames:
    - argocd.tokyo0.cybozu-ne.co
