apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: teleport-proxy-selfsign
  namespace: teleport
  labels:
    app.kubernetes.io/name: teleport
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: teleport-proxy-ca
  namespace: teleport
  labels:
    app.kubernetes.io/name: teleport
spec:
  secretName: teleport-proxy-ca
  duration: 87600h0m0s # 10y
  issuerRef:
    name: teleport-proxy-selfsign
  commonName: "ca.proxy.teleport"
  isCA: true
---
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: teleport-proxy-ca
  namespace: teleport
  labels:
    app.kubernetes.io/name: teleport
spec:
  ca:
    secretName: teleport-proxy-ca
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: teleport-proxy-tls
  namespace: teleport
  labels:
    app.kubernetes.io/name: teleport
spec:
  secretName: teleport-proxy-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: teleport-proxy-ca
  commonName: teleport.gcp0.dev-ne.co
  dnsNames:
    - teleport.gcp0.dev-ne.co
