apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machines-endpoints
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "update", "create"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["machines-endpoints-bmc"]
