apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: controller-pdb
  namespace: topolvm-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
