apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: teleport-proxy-tls
  namespace: teleport
spec:
  secretName: teleport-proxy-tls
  issuerRef:
    kind: ClusterIssuer
    name: clouddns
  commonName: teleport.stage0.cybozu-ne.co
  dnsNames:
    - teleport.stage0.cybozu-ne.co
