apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: contour-tls
  namespace: ingress
spec:
  dnsNames:
    - contour
    - contour.ingress-bastion
    - contour.ingress-bastion.svc
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: envoy-tls
  namespace: ingress
spec:
  dnsNames:
    - envoy
    - envoy.ingress-bastion
    - envoy.ingress-bastion.svc
