apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: contour-leaderelection
  namespace: projectcontour
subjects:
- kind: ServiceAccount
  name: contour
  namespace: ingress-bastion
