apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-for-ss
  namespace: ceph-for-ss
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: topolvm-provisioner
        resources:
          requests:
            storage: 10Gi
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  cephVersion:
    image: quay.io/cybozu/ceph:14.2.8.4
    allowUnsupported: false
  dashboard:
    enabled: false
    ssl: true
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 1
        resources:
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 5Gi
              # IMPORTANT: Change the storage class depending on your environment (e.g. local-storage, gp2)
              storageClassName: local-storage
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
        placement:
          tolerations:
            - key: cke.cybozu.com/role
              operator: Equal
              value: storage
              effect: NoExecute
